language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - travis_retry composer update

script:
  - vendor/bin/phpunit

jobs:

  include:
    - stage: Code Quality
      script:
        - ./vendor/bin/phpcs
